# Generated by Django 6.0.2 on 2026-02-12 10:12

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Системное имя (telegram, whatsapp, max и т.д.).', unique=True)),
                ('name', models.CharField(help_text='Человекочитаемое название базы.', max_length=100)),
                ('default_daily_limit', models.PositiveIntegerField(default=0, help_text='Базовый дневной лимит выдачи контактов одному пользователю.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в списках.')),
            ],
            options={
                'verbose_name': 'Тип базы',
                'verbose_name_plural': 'Типы баз',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Системное имя типа лида.', unique=True)),
                ('name', models.CharField(help_text='Человекочитаемое название типа.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тип лида',
                'verbose_name_plural': 'Типы лидов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('support', 'Поддержка'), ('admin', 'Администратор')], default='user', help_text='Роль в системе (права доступа).', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрен'), ('banned', 'Заблокирован')], default='pending', help_text='Статус модерации пользователя.', max_length=20)),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='При необходимости — связка с Telegram-пользователем.', null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='Сырые данные контакта (юзернейм, телефон, ссылка и т.п.).', max_length=255)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='Когда контакт был выдан пользователю.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Можно ли контакт выдавать пользователям.')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Пользователь, которому выдан контакт.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_contacts', to=settings.AUTH_USER_MODEL)),
                ('base_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.basetype')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'unique_together': {('base_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, help_text='Источник лида или доп. описание (например, ссылка на объявление).', max_length=255)),
                ('comment', models.TextField(blank=True, help_text='Комментарий пользователя или менеджера.')),
                ('attachment', models.FileField(blank=True, help_text='Скриншот/файл, подтверждающий лид.', null=True, upload_to=core.models.lead_attachment_upload_to)),
                ('base_type', models.ForeignKey(blank=True, help_text='Из какой базы взят контакт (если известно).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.basetype')),
                ('contact', models.ForeignKey(blank=True, help_text='Связанный контакт (если он есть в базе).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('lead_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.leadtype')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
            },
        ),
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, help_text='Краткая тема обращения.', max_length=255)),
                ('is_closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Диалог поддержки',
                'verbose_name_plural': 'Диалоги поддержки',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_from_support', models.BooleanField(default=False, help_text='True, если сообщение от поддержки/менеджера.')),
                ('text', models.TextField(blank=True)),
                ('sender', models.ForeignKey(blank=True, help_text='Автор сообщения (пользователь или сотрудник поддержки).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportthread')),
            ],
            options={
                'verbose_name': 'Сообщение поддержки',
                'verbose_name_plural': 'Сообщения поддержки',
            },
        ),
        migrations.CreateModel(
            name='UserBaseLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_daily_limit', models.PositiveIntegerField(default=0, help_text='Дополнительные контакты в день сверх базового лимита.')),
                ('base_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_limits', to='core.basetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дополнительный лимит по базе',
                'verbose_name_plural': 'Дополнительные лимиты по базам',
                'unique_together': {('user', 'base_type')},
            },
        ),
    ]
