# Generated by Django 6.0.2 on 2026-02-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead_raw_contact_and_initial_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Вложение: скриншот, файл.', null=True, upload_to='support/%Y/%m/%d/'),
        ),
    ]
