# Generated by Django 6.0.2 on 2026-02-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_support_message_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportthread',
            name='subject',
        ),
        migrations.AddField(
            model_name='supportthread',
            name='last_read_at',
            field=models.DateTimeField(blank=True, help_text='Когда сотрудник поддержки последний раз открывал диалог (для пометки «прочитано»).', null=True),
        ),
    ]
