# Generated by Django (ContactRequest model)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_support_thread_remove_subject_add_last_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("pending", "Ожидает"), ("resolved", "Обработано")], default="pending", max_length=20)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("base_type", models.ForeignKey(blank=True, help_text="База, по которой запрашивает лимит (если известна).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contact_requests", to="core.basetype")),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_contact_requests", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contact_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Заявка на контакты",
                "verbose_name_plural": "Заявки на контакты",
                "ordering": ["-created_at"],
            },
        ),
    ]
