# Generated by Django 6.0.2 on 2026-02-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reset_extra_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, help_text='Баланс пользователя (руб.). Начисляется вручную админом.'),
        ),
    ]
