# Generated by Django 6.0.2 on 2026-02-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_withdrawal_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_details',
            field=models.TextField(blank=True, help_text='Способ вывода: номер карты, телефон с банком и т.п.'),
        ),
    ]
