# Generated by Django 6.0.2 on 2026-02-15 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_withdrawal_payout_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Причина отклонения (если статус «Отклонён»).'),
        ),
        migrations.AddField(
            model_name='lead',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Когда модератор вынес решение.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Кто проверил лид.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='rework_comment',
            field=models.TextField(blank=True, help_text='Что доработать (если статус «На доработке»).'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('rework', 'На доработке')], default='pending', help_text='Статус модерации лида.', max_length=20),
        ),
    ]
