# Generated by Django 6.0.2 on 2026-02-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lead_status_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportthread',
            name='user_last_read_at',
            field=models.DateTimeField(blank=True, help_text='Когда пользователь последний раз открывал чат (для уведомления о новых сообщениях от поддержки).', null=True),
        ),
    ]
