# Generated by Django 6.0.2 on 2026-02-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lead_normalized_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Включить хранение медиа в S3')),
                ('bucket_name', models.CharField(blank=True, help_text='Имя бакета (Timeweb Cloud S3)', max_length=255)),
                ('access_key_id', models.CharField(blank=True, max_length=255, verbose_name='Access Key ID')),
                ('secret_access_key', models.CharField(blank=True, max_length=255, verbose_name='Secret Access Key')),
                ('endpoint_url', models.URLField(blank=True, help_text='Например https://s3.timeweb.cloud', max_length=500)),
                ('region_name', models.CharField(blank=True, default='ru-1', max_length=64)),
            ],
            options={
                'verbose_name': 'Настройки хранилища медиа (S3)',
                'verbose_name_plural': 'Настройки хранилища медиа (S3)',
            },
        ),
    ]
